### PR TITLE
Add color to severity in REPL reporter

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by puffnfresh** [comment]
screen shot 2014-09-24 at 7 04 56 pm

**Comment by folone** [comment]
that's beautiful

**Comment by fommil** [comment]
will there be a way to turn this off for, e.g. repl sessions in emacs?

**Comment by puffnfresh** [comment]
@fommil colours are turned off under comint-run - dunno if that's cause JLine doesn't kick in or isAnsiSupported returns false but it's definitely not active.

**Comment by fommil** [comment]
Cool. As long as the escape sequences don't show up that's fine.

**Comment by puffnfresh** [comment]
:shipit:

**Comment by jsuereth** [comment]
nice!

**Comment by milessabin** [comment]
If you would like to resurrect this issue/PR please rework it as a PR against Lightbend Scala 2.12.x (ie. scala/scala).

**Pull request closed without merging**
