### PR TITLE
Add support for literal Byte and Short values.

### PR DESCRIPTION
**Pull request by puffnfresh**
This commit reserves the [zZ] and [sS] suffixes for Byte and
Short literals, respectively. These work exactly like Long
literals, which were already denoted with [lL].

For example, you can say:

``` scala
val zero = 0Z
val bytes = List(23Z, 23Z, 0Z, 0Z, 111Z, -54Z, 19Z, 17Z)
```

This commit does not permit literal unsigned bytes, so 255Z and
0xffZ are not legal.

The choice of Z may seem strange, but B will not work for
hex constants (0x10B would be ambiguous) so Z seemed like a
good choice.

### CODE REVIEW

**Comment by non** [comment]
As the commit's author, I say :+1:

**Comment by djspiewak** [comment]
Someone please fix my ignorance, but doesn't the `[bB]` suffix suffice for byte literals?

**Comment by non** [comment]
@djspiewak Did you see the commit message? `0x10B` would be ambiguous between an integer literal and a byte literal.

**Comment by djspiewak** [comment]
What? Reading justifications?! Pshshshshshsh. :-)

That does make sense; thanks.

**Comment by Blaisorblade** [comment]
@puffnfresh Weren't we waiting for CI etc. before merging?

**Comment by puffnfresh** [comment]
@Blaisorblade this is a commit which we tested pretty well a few months ago. I'll definitely be waiting for CI before doing much more.

**Comment by Blaisorblade** [comment]
Alright, sorry for the noise!

**Comment by loverdos** [comment]
Did the Z suffix come out of some searching around or is it (pseudo) random? For example, here is what #fsharp has and they do cover a lot of cases http://msdn.microsoft.com/en-us/library/dd233193.aspx. What does Haskell say on this? Other languages?

**Comment by propensive** [comment]
We chose it because A-F aren't available, and because it's associated with the Integers in math (even though we're using it to represent a tiny subset of them). http://en.wikipedia.org/wiki/Integer

**Pull request merged**
