### PR TITLE
Removed obsolete functionality

### PR DESCRIPTION
**Pull request by mxswd**
Now that we have macros a lot of compiler functionality is obsolete.
- Removed most of the java beans.
- Removed scala xml.
- Removed not implemented exception.
- ??? now throws a runtime exception, the same as sys.error (another function of type Nothing).

### CODE REVIEW

**Comment by Blaisorblade** [comment]
:-1: on `NotImplementedException`, that's useful to know that your failure is just because of `???`.
Why is that related to macros anyway?

:+1: on Scala XML. No clue on Java Beans, never used them.

**Comment by djspiewak** [comment]
Again, compatibility questions here.  If we are ok not being able to compile code which successfully compiles with scalac, then sure go for it, but that is precisely the distinction you would be drawing here.

**Comment by Blaisorblade** [comment]
Agreed, but removing XML literals is relatively uncontroversial (apart from legacy reasons), so our guidelines should support such cases. See #14.

However, we might want to ensure though that there's a migration path: I know macro enable creating one, but the with the same argument.

**Comment by puffnfresh** [comment]
@djspiewak I've been under the impression that all scalac source will be compilable under typelevelc and I think it's very important. We need to figure this out as part of #14.

**Comment by Blaisorblade** [comment]
@puffnfresh This one could go under `-Xfuture:donGiovanni` since it's even in the [Typesafe Scala roadmap](http://www.scala-lang.org/news/roadmap-next). And in this form, it could conceivably even go upstream.
Not that we can really support Don Giovanni since it's DOT-based — but this is unrelated.

**Comment by mxswd** [comment]
@Blaisorblade of the 4 PRs I made yesterday, this is the one concerned with the main compiler source base. So yes, ??? Is unrelated to macros.

I would expect `sys.error("unimplemented")` to throw the same type of exception as `???`. So I fixed that.

**Pull request closed without merging**
