### PR TITLE
update documentation for ENSIME

### PR DESCRIPTION
**Pull request by fommil**
ENSIME support for hacking on scala seems to have rotted, so this is to bring it up to date.

(The following is answered already)

~~I have a PR https://github.com/ensime/ensime-server/pull/622 which allows me to superficially hack on the the `scala-library` after issuing an `ant` on a clean checkout. We're also discussing a few further issues that we might need to address. In any case, I need some help from seasoned scala contributors on this PR:~~
1. ~~which modules do you want to support? The previous config only supported `library`, `reflect` and `compiler` (I consider `asm` to be a module since you're compiling from source... so anything else like that is necessary)~~
2. ~~what is the dependency tree of those modules?~~
3. ~~where are your test sources associated to each module? I'm completely lost~~
4. ~~where do output classes (and test-classes) associated to each module go? (I could only find the class output for `asm`)~~
5. ~~which version of scala is supposed to be used for a given branch? e.g. does the library for 2.11 actually use 2.11 or is it bootstrapped off 2.10? (or is it just the compiler that needs to be bootstrapped?). This might imply the need to create two separate `.ensime` configurations: an ENSIME project only supports one version of scala (it has a tightly coupled in-process presentation compiler).~~
6. ~~I guess in everything pre 2.12 the official java version is 1.6.0 so you need the `forkjoin.jar`. You haven't attached the sources, can somebody please do so? (and also, is it just the library that depends on it?)~~

~~And maybe this is a can of worms, but what does one type to produce `.class` output from library/compiler/reflect in a quick dev cycle? Will it completely break everything if we add compiled library/compiler/reflect classes to the presentation compiler classpath or should we just stick to a pure full source instance?~~

### CODE REVIEW

**Comment by milessabin** [comment]
add to whitelist

**Comment by fommil** [comment]
I've had an offline discussion and I have a much better idea of which modules are needed to be supported and what the limitations are going to be. I'll do a force push when we're in a better position in the ENSIME codebase to support this properly.

**Comment by MasseGuillaume** [comment]
@fommil what about merging the sbt build from paul then using sbt-ensime ?

**Comment by fommil** [comment]
@MasseGuillaume that is unlikely to work. There is a lot of subtle dependency tracking going on in this project and it requires us to add some functionality on the server side.

**Comment by fommil** [comment]
if you guys are happy with the change to the `build.xml` then this is good to merge :smile:

**Comment by puffnfresh** [comment]
@fommil awesome stuff, I'll review after the build goes green.

**Comment by fommil** [comment]
I wonder if perhaps everything below the `repl` module should be its own project instead of part of the monolith, but hopefully this gives enough detail to allow people to do that if they wish.

**Comment by fommil** [comment]
is this the sort of thing that would be useful to port back onto typesafe scala?

**Comment by milessabin** [comment]
Probably, yes.

**Comment by adriaanm** [comment]
Yes, please!

**Pull request merged**
