### PR TITLE
A simple travis file running the build-test

### PR DESCRIPTION
**Pull request by rorygraves**

### CODE REVIEW

**Comment by puffnfresh** [comment]
Awesome stuff, thank you! Hopefully the build passes.

**Comment by milessabin** [comment]
Unfortunately not: https://travis-ci.org/typelevel/scala/builds/35944845.

But we have something to take back to Travis now :-)

**Comment by puffnfresh** [comment]
@milessabin looks like an OOM killer came in. I guess Linux overcommits the 2GB to our tests?

**Comment by aloiscochard** [comment]
FWIW, the tests consume ~4GB when running on a vm (that's with partest.threads=1)

**Comment by puffnfresh** [comment]
@aloiscochard we're not setting `partest.threads` - that's something we should do, right?

**Comment by aloiscochard** [comment]
@puffnfresh yes absolutely, otherwise it require even more memory! (virtual not necessary used, as it start lot of vm in parallel)

For jenkins I had to put it under a `D` param, as `-Dpartest.threads=1` to the jvm settings and that did the work.

Here is the complete JVM settings in the jenkins job:
`-Xms1g -Xmx1g -XX:MaxPermSize=512m -Dpartest.threads=1`

I hope that will help!

**Pull request merged**
