### PR TITLE
Update README to be specific to Typelevel

### PR DESCRIPTION
**Pull request by puffnfresh**
Uses @djspiewak's definitions of compatibility. Adds instructions for
publishing locally.

### CODE REVIEW

**Comment by djspiewak** [comment]
:+1:

Only concern is that my compatibility guidelines use the "tlc" acronym without really defining it.  It might also be worth editing them down slightly so they are less verbose.

**Comment by non** [comment]
I am fine with merging this provisionally. Like @djspiewak says we should decide if we want to use that acronym, and if so what it means. I also think we need to have a few more conversations before we totally fix what the compatibility requirements mean.

**Comment by djspiewak** [comment]
> I also think we need to have a few more conversations before we totally fix what the compatibility requirements mean.

:+1:  I didn't intend my list of requirements to be final, they just were the first thought and an attempt to start the discussion.  The requirements listed _are_ very strict.  There's certainly room to do a lot of stuff, but many things (such as straight-up deleting stdlib APIs) will be impossible, though the same effect will be achievable by instead _moving_ "deleted" APIs into a "scala-compat" library.

Anyway, the larger point is that we should think very carefully about the restrictions we impose on ourselves, because the implications for the future of this project (and the future of Scala in general) are very, very serious.

**Comment by puffnfresh** [comment]
@djspiewak I only think we need to be careful about one thing: we can always be less restrictive in the future but it's very hard to become more restrictive.

**Comment by djspiewak** [comment]
@puffnfresh Absolutely.

**Comment by puffnfresh** [comment]
Add to whitelist

**Pull request merged**
