### PR TITLE
Allow currency symbols in identifiers

### PR DESCRIPTION
**Pull request by propensive**

### CODE REVIEW

**Comment by propensive** [comment]
This wasn't massively complicated...

**Comment by non** [comment]
Consider adding at least one test that proves they used to be forbidden and now are allowed?

**Comment by propensive** [comment]
Good call. It's highlighted a parsing issue with combining currency symbols and other symbols in the same identifiers which I'll need to fix.

**Comment by puffnfresh** [comment]
add to whitelist

**Comment by retronym** [comment]
Just as a heads up if these sort of changes want to find their way upstream, we ask that the spec is updated in the same PR as the implementation. That was a big part of the motivation to markdown-ize it and bring it into `scala/scala`.

**Comment by propensive** [comment]
Thanks, Jason. When I get round to fixing this properly (it's got various
issues), I'll include the spec changes too.

On 2 October 2014 06:51, Jason Zaugg notifications@github.com wrote:

> Just as a heads up if these sort of changes want to find their way
> upstream, we ask that the spec is updated in the same PR as the
> implementation. That was a big part of the motivation to markdown-ize it
> and bring it into scala/scala.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/typelevel/scala/pull/48#issuecomment-57583830.

## 

Jon Pretty | @propensive

**Comment by propensive** [comment]
This should be ready to go. Could someone (maybe @puffnfresh?) give it a quick review and press the big green button?

**Comment by milessabin** [comment]
If you would like to resurrect this issue/PR please rework it as a PR against Lightbend Scala 2.12.x (ie. scala/scala).

**Comment by propensive** [comment]
Maybe if I find time later... ;)

What was the status of the identifiers-with-primes change? Could these two be rolled into the same PR?

**Comment by milessabin** [comment]
I'm wiping the slate and starting again with a new policy around inclusion (expect an announcement soon). The primes as identifiers change isn't going to be in the 2.12.0-RC1 release. It would make sense to combine that change with this one and submit both upstream at that the same time.

**Pull request closed without merging**
