### PR TITLE
Backport LUBs for  SIP-23

### PR DESCRIPTION
**Pull request by folone**
This adds some fixes for SIP-23 that @adriaanm introduced recently, as well as some tests. /cc @propensive

### CODE REVIEW

**Comment by propensive** [comment]
Thanks for the explicit instruction! :)

**Comment by folone** [comment]
:) No idea why build failed, btw: for me only two tests don't pass.

**Comment by folone** [comment]
Ok, was able to reproduce. Looking into it.

**Comment by folone** [comment]
Looks like https://github.com/adriaanm/scala/commit/61a16f54b64d1bf020f36c2a6b4baff58c6ec70d does not bootstrap. I've removed it from this PR, so it only contains LUBs for singleton types. The build bootstraps now, let's see if it actually passes: http://typelevel-ci.orexio.org/job/typelevel-scala-pr/44/

**Comment by folone** [comment]
And it passed: http://typelevel-ci.orexio.org/job/typelevel-scala-pr/44/console /cc @propensive

**Comment by adriaanm** [comment]
Yeah, we actually have a `global.asInstanceOf[otherGlobal]` where `global != otherGlobal`...

**Comment by adriaanm** [comment]
That last commit translates asInstanceOf to what the pattern matcher does, which is strictly speaking how it is spec'ed :-/

**Pull request closed without merging**
