### PR TITLE
Topic/typelambda cleanup v0

### PR DESCRIPTION
**Pull request by non**
This PR is intended to fix the issues that @retronym and @adriaanm pointed out in #71.

I'm not sure I'll be able to introduce new AST nodes here, but I want to leave the PR open a bit to make sure to add lots of test cases, try to fix (or at least document) any weird behavior, etc.

### CODE REVIEW

**Comment by retronym** [comment]
Here's a sketch of what we'd need to to to represent a type function as a `TypeDef`

https://github.com/retronym/scala/compare/typelevel:2.11.x...2.11.x?expand=1

Note that this fixes the problems of unwanted rebinding of `ThisTypes` within the bounds of the parameters to the synthetic template. But as you can see it is still a bit messy because I'm typechecking that `TypeDef` down to a `TypeTree`, and a few places currently expect the `tpt` of a type application to be a tree with a symbol.

Anyway, I just wanted to dump that in case it helps. Sounds like documenting the limitations will be fine for the short term (declaring bounds in type lambdas isn't _all_ that common).

**Comment by non** [comment]
Thanks!

Do you see any immediate downsides to just grabbing your implementation and trying to make it real? If it's a better approach I'm happy to hack on it until the tests pass, etc.

**Comment by adriaanm** [comment]
@retronym's approach LGTM (as a stepping stone towards type functions having their own AST node eventually)

**Comment by retronym** [comment]
I wasn't that happy with the `TypeDef` hack (in particular the fickle override of `isType` in `TypeDef`).

Here's how it would look with a dedicated AST node:

  https://github.com/retronym/scala/compare/typelevel:2.11.x...topic/type-function?expand=1

I've only quickly smoke tested this change, it deserves needs more testing (e.g. of tree printing.)

In that branch, I've let the `TypeFunction` node remain after typechecking, rather than collapsing it down to a `TypeTree` over a `PolyType`. I believe this is the correct thing to do, otherwise the symbols of the type functions type parameters will be orphaned after typer (that is, they will be owned by a symbol whose `DefTree` no longer encloses the type parameter.

Allowing the tree to persist beyond typer does introduce some risk, as it could trip up code in later compiler phases, macros, or compiler plugins. But that is the nature of the game when changing the AST.

**Pull request merged**
