### PR TITLE
Microsite for Typelevel Scala fork

### PR DESCRIPTION
**Pull request by juanpedromoreno**
This PR brings a microsite for the Typelevel for of the Scala Compiler. It's made thanks to the https://github.com/47deg/sbt-microsites plugin and the resources provided in this PR.

It takes as main documentation the README file from https://github.com/typelevel/scala. We've set up the initial URL at `http://typelevel.org/scala` but it could be changed at your convenience.

If you want to test locally you need [Jekyll](https://jekyllrb.com/) locally, depending on your platform, you might do this with:

``` bash
yum install jekyll

apt-get install jekyll

gem install jekyll
```

Once you have installed it, you could perform the following steps:
- Build the microsite:

``` bash
sbt "makeMicrosite"
```
- Then, to visualize the website in your browser, in a shell, navigate to the generated site directory in `target/site`
- Start jekyll with `jekyll serve`
- Navigate to http://localhost:4000

Please, review at your convenience. Many thanks!

Join-effort from the 47Deg team :)

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
This is the proposal:

scala

**Comment by milessabin** [comment]
This is great stuff ... thanks!

Can you say how this works in conjunction with typelevel.org?

**Comment by juanpedromoreno** [comment]
From the top of my head, nothing has changed from the previous version,
since all paths are the same, i.e. on the same segment `cats`. If I'm not
missing anything, the site it'd prepared to be deployed on
typelevel.org/cats.

Does it make sense?

**Comment by milessabin** [comment]
The org.typelevel site is a completely separate repo from this one, with it's own Jekyll build process ... I can merge this PR, but what mechanism are you proposing for including this content under org.typelevel?

**Comment by juanpedromoreno** [comment]
I got confused this thread with the other one opened at https://github.com/typelevel/cats/pull/1369, sorry about that!.

I'm not completely sure how [typelevel.github.com](https://github.com/typelevel/typelevel.github.com) works, but maybe we could push this microsite to `gh-pages` branch within https://github.com/typelevel/scala and distribute the site in the same way as `cats`, for instance, under http://typelevel.org/scala.

In that case, we could change the permanent link here: https://github.com/typelevel/typelevel.github.com/blob/master/_projects/scala.md

Does it make sense?

**Comment by juanpedromoreno** [comment]
@larsrh @milessabin This is ready to go if looks good to you. Please, take a look at the documentation to see deeper info about how to publish it (https://47deg.github.io/sbt-microsites/docs/build-the-microsite.html). Thanks!

**Comment by larsrh** [comment]
Thanks @juanpedromoreno! I'll merge and publish this by hand for now (so that we can get it out for people to see). I'll try to find some time to automate publishing.

**Comment by larsrh** [comment]
@juanpedromoreno For some reason, the generated HTML looks off: the multi-line code snippets don't get properly formatted. Could you take a look please?

screenshot_20160924_234304

**Comment by juanpedromoreno** [comment]
Potentially, it could be because of an old Ruby/Jekyll version. Please,
could you check it and trying again with "sbt publishMicrosite"? Thanks.

**Comment by larsrh** [comment]
I did `sbt publishMicrosite`. I thought I had a recent version of Jekyll installed (3.0.2), but after I've updated to (3.2.1), it's rendering correctly. Thanks!

**Comment by dwijnand** [comment]
You might want to consider setting up Bundler in the repo, instead of relying on whatever you have installed system-wide.

Here's how I did it for the ENSIME website: https://github.com/ensime/ensime.github.io/pull/24. (note some of that initial config later changed).

**Comment by milessabin** [comment]
Looks good.

What's the mechanism for updating the site when the README changes?

**Comment by juanpedromoreno** [comment]
Looks great @dwijnand 

For the sbt-microsites docs, as another alternative, we are doing auto-publish each time we merge something in master branch.

https://github.com/47deg/sbt-microsites/blob/master/.travis.yml
https://github.com/47deg/sbt-microsites/blob/master/scripts/publishMicrosite.sh

**Comment by larsrh** [comment]
@milessabin No mechanism just yet. I'll try to get the automation set up next week.

**Comment by juanpedromoreno** [comment]
In the alternative that we've implemented, we just need to generate an `ssh-key`, adding it to this Github account (https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/). Then, Travis and the script commented before would do the rest of the work.

**Comment by larsrh** [comment]
@juanpedromoreno Yeah, I just resurrected our bot account, so this is precisely what we're going to do :smile:

**Pull request merged**
