### PR TITLE
Added -Zexplicit-implicit-type-ascriptions

### PR DESCRIPTION
**Pull request by propensive**
With the flag enabled, every implicit val/var/def definition must have
an explicit type ascription, otherwise an error is emitted.

### CODE REVIEW

**Comment by puffnfresh** [comment]
Do the type ascription changes to the compiler and stdlib need to be made? They won't have the flag enabled, right?

**Comment by propensive** [comment]
Flag's not enabled, so they're not required, no.

But they are probably a good thing, and the work's been done, so I've left them in, as the binary compatibility tests all pass.

**Comment by Blaisorblade** [comment]
Why not enable the flag then? Otherwise this change will not be maintained.

**Comment by puffnfresh** [comment]
My minor concern is this could make merging Typesafe scalac a little annoying but probably not.

**Comment by retronym** [comment]
[`srewrite`](https://github.com/samuelgruetter/srewrite), an experimental source code migration tool, supports automatically adding type annotations to implicits. @odersky would like to move to this policy in  dotc, so we're quite happy to have a lint warning for non-annotated implicits over in scala/scala sooner rather than later.

**Comment by retronym** [comment]
Oh, and we'd definitely appreciate the patch with the explicit annotations throughout our code!

**Comment by som-snytt** [comment]
So I just wrote

```
  import scala.io.Codec.UTF8
  implicit def `we love utf8` = UTF8
```

and obviously I don't want to add an import so I can write `: Codec`.  Isn't there an implicit import PR floating around somewhere that makes this angle less annoying?

This was in a test, BTW,  also subject to migration.

**Comment by propensive** [comment]
@retronym The patch should ascribe explicit types to all the instances that flagged as errors during compilation of the compiler and standard library, with one exception (which unfortunately I haven't been able to find in ten minutes of trying to find it again): there's a method somewhere which returns an implicit def which returns an instance of a class defined locally to that method. I think this means the implicit will get a structural type inferred, but it was sufficiently horrible that I stopped there...

**Comment by propensive** [comment]
@som-snytt I'm not sure I'd want an implicit import for such a specific use case, though I agree it's annoying. Suggestions welcome...

**Comment by milessabin** [comment]
If you would like to resurrect this issue/PR please rework it as a PR against Lightbend Scala 2.12.x (ie. scala/scala).

**Pull request closed without merging**
