### PR TITLE
Assets microsite

### PR DESCRIPTION
**Pull request by israelperezglez**
@raulraja could you review please?

### CODE REVIEW

**Comment by raulraja** [comment]
Let's use the same font they use in the Typelevel.org site.

**Comment by milessabin** [comment]
This looks like it's a work in progress? Let me know when you're ready for it to be merged :-)

**Comment by raulraja** [comment]
Yeah sorry Miles, it was supposed to be a PR to our own fork until ready.
Will close and resubmit when ready.

**Comment by milessabin** [comment]
No worries :-)

**Pull request closed without merging**
