### PR TITLE
Backport code from typesafe scala

### PR DESCRIPTION
**Pull request by folone**
2.11.4 was just staged: https://groups.google.com/forum/#!topic/scala-internals/y890GcpjONE. Time to backport the changes?

### CODE REVIEW

**Comment by folone** [comment]
Tests seems to pass http://typelevel-ci.orexio.org/job/typelevel-scala-pr/37/

**Comment by milessabin** [comment]
+1

**Comment by non** [comment]
It builds and passes tests, :+1:

**Comment by folone** [comment]
Added more commits (including bumping to 2.11.5-SNAPSHOT): http://typelevel-ci.orexio.org/job/typelevel-scala-pr/38/

**Comment by folone** [comment]
Closing this, as #87 has all this incorporated.

**Pull request closed without merging**
