### PR TITLE
Update microsite with documentation, take 2!

### PR DESCRIPTION
**Pull request by pvillega**
This is a follow up on https://github.com/typelevel/scala/pull/123 . It adds documentation on working with the compiler to the microsite.

Credit to @diesalbla and @rorygraves for a rework of the documentation contents. Any mistakes introduced are my fault :)

A note: the 'edit' links at the bottom of the pages have been added by hand as I wasn't sure how to translate the jekyll template to the microsite (it was getting convoluted). They should work, but needs to be improved in the future.

Let me know if you want some changes or feel free to edit files at will to follow any guidelines/rules I missed!

### CODE REVIEW

**Comment by SethTisue** [comment]
trees and symbols are documented at http://docs.scala-lang.org/overviews/reflection/symbols-trees-types.html

**Comment by milessabin** [comment]
Awesome start @pvillega! :-)

Maybe @diesalbla and @larsrh could review from a microsite/typelevel.org integration PoV?

**Comment by pvillega** [comment]
@SethTisue thanks for that link, that may be the next PR, let's keep it small :)

**Comment by SethTisue** [comment]
@pvillega my point is that in this PR, there are stub pages that indicate that someone ought to write some documentation on trees and symbols. there are two problems here:

1) such documentation already exists, so you at least ought to link to it so people know about it
2) such documentation already exists, so it's questionable whether it even makes sense to encourage someone to write additional similar documentation in a Typelevel Scala specific context

2 might be debatable, but 1 seems inarguable?

**Comment by larsrh** [comment]
> Maybe @diesalbla and @larsrh could review from a microsite/typelevel.org integration PoV?

Looks good with respect to sbt-microsite.

**Comment by pvillega** [comment]
@SethTisue you have a point, so I've added the link to the relevant pages.

Mind you, I am aware the text in those sections can be improved, but this is just a first approach people can build upon. That said, if there are any other major issues, please let me know

**Comment by milessabin** [comment]
Awesome! Merging :-)

**Comment by SethTisue** [comment]
👍

**Comment by larsrh** [comment]
I'm afraid these links aren't up-to-date anymore. Any takers on updating them?

**Pull request merged**
