### PR TITLE
Basic implementation of 42.type

### PR DESCRIPTION
**Pull request by folone**
Hey folks,

Sorry this took so long: got swamped with all the things that happened while I was away from the internet.
As discussed in #18, sending the first part of `42.type` – without a way to materialize inhabitants of singleton types.

Please take a look @milessabin @puffnfresh @non

### CODE REVIEW

**Comment by propensive** [comment]
Thanks, George! :)

**Comment by puffnfresh** [comment]
Thank you! Looks pretty great, I'll take a close look today.

**Comment by milessabin** [comment]
Good stuff ... I'll take a look at it over the weekend.

**Comment by milessabin** [comment]
@paulp are there any specific issues that you'd like to highlight?

**Comment by paulp** [comment]
That's what I was doing. Unless this iPad client has betrayed me I left the preceding comment on the line I meant. Look for the var.

**Comment by milessabin** [comment]
@paulp It looks like it's just linked to the whole commit ... I might be missing something, but I don't see a comment on any particular lines.

**Comment by relrod** [comment]
@milessabin If you go to the issue view that has all the comments on it (including this one), go to @paulp's comment and it says "paulp commented on 7e59605 src/reflect/scala/reflect/internal/Types.scala 12 hours ago" - click on the filename and it will bring you to the file he commented on, though it doesn't seem to auto-scroll to the specific line.

Anyway, because I'm a nice person (at least once in a while :P) here's a [direct link](https://github.com/typelevel/scala/commit/7e596059f7a0c2b2c6ae16f5bfe6f8a8a1f993ba#diff-ecaa4198a04261cd0e00a708b695eafbR261) to the line (and comment beneath it). ;)

**Comment by milessabin** [comment]
@CodeBlock Thanks. @paulp assuming the mutable state were eliminated, would you be happy?

**Comment by folone** [comment]
@paulp Agree, will look into this. There's a single place where `asDeclaredSingleton` is used: `scala.tools.nsc.typechecker.Typers`, line 5117. I tried making `isDeclaredSingleton` a `def`, and changing that block to

``` scala
tree setType {
  if (tree.isLiteral) new SimpleTypeProxy {
    override def underlying = refTyped.tpe.resultType
    override def isDeclaredSingleton = true
  }
  else refTyped.tpe.resultType
}
```

That didn't work though. Will continue looking.

**Comment by paulp** [comment]
It won't be that easy, that's how a var ended up there in the first place. You can't just attach state to a Type and expect things to work. That's just as true of a def in a subclass as it is of a naked var. Everywhere that types are propagated, duplicated, created, everything must propagate that state. The fact that it kind of works because the state survives a while just makes it worse, because it plants all kinds of bugs for the next guy to enjoy. 

I would suggest annotating the type except the compiler arbitrarily discards annotations on the way through TypeMaps. That is the cause of untold bugs. I fixed it in policy actually. I'm not sure what to suggest for reliably attaching information to a Type. The fact that something so basic admits no direct solution is why I don't work on other peoples' terms (or their types) anymore.

**Comment by milessabin** [comment]
See also #51.

**Comment by puffnfresh** [comment]
add to whitelist

**Comment by puffnfresh** [comment]
Build is green, what can we do to make this ready for merging?

**Comment by milessabin** [comment]
I think the main thing was the mutable state issue ... @folone, have you been able to make any progress on that?

**Comment by folone** [comment]
Did not get around to exploring what @paulp suggested. Will try to do that over the weekend.

**Comment by folone** [comment]
Rebased onto the latest `2.11.x` in the meantime.

**Comment by retronym** [comment]
Here's what we have today:

image

`SingletonType` marks a term as `stable`. For a term `f` with a stable type, the program `{ g(f); h(f) }` can be rewritten as `{ val temp = f; g(temp); g(temp); }` (well, approximately, if `g` or `h` have prefixes you need to evaluate them first).

`ConstantType` means that a term need not be evaluated at all, the value in its type can be used instead. This has been to support ["constant expressions"](http://www.scala-lang.org/files/archive/spec/2.11/06-expressions.html#constant-expressions) / ["constant value definitions"](http://www.scala-lang.org/files/archive/spec/2.11/04-basic-declarations-and-definitions.html#value-declarations-and-definitions). Note that "constant types" themselves are not specced in [Types](http://www.scala-lang.org/files/archive/spec/2.11/03-types.html), they currently an internal implementation detail of constant expressions.

I had previously thought it would be sufficient to change our constant folder to act not on the types, but rather on the terms. so `Literal(Const(42)) + Literal(Const(42))` could fold to 84, but `q"foo"{42.type} + q"foo"{42.type}` would not. That's what I prototyped in [topic/const-type-fold](https://github.com/retronym/scala/compare/topic/const-type-fold).

But on second thoughts, I now wonder if we instead will need to introduce an alternative to `ConstantType` that doesn't imply inlinability.

I think it would be really clarifiying to work out a few of these design issues by considering how they would be specced.

**Comment by folone** [comment]
Hey folks,

Just letting you know that I'm still here. I have a working solution (no `var`s) along the lines of what @retronym suggests: a type similar to `ConstantType`, that does not imply constant folding. It still has some rough edges though. I'm also on the road at the moment, and have limited internet access. Will push what I've got when I'm back on Monday, so this can be further discussed. By the way, guess this change will also require changes to the spec. Will work on that too.

**Comment by puffnfresh** [comment]
:fireworks:

**Comment by non** [comment]
Awesome! This sounds great, thanks!

**Comment by paulp** [comment]
If you add a new subclass of Type, you may soon see why they call it the expression "problem".

**Comment by folone** [comment]
Pushed that fix. Here are the rough edges I was talking about:

``` scala
scala> var t: 7.type = 7
<console>:7: error: assignment to non variable
       var t: 7.type = 7
           ^
```

and

``` scala
scala> def test: 23.type = {
     | println("PANDA!")
     | 23
     | }
<console>:7: error: type mismatch;
 found   : Int
 required: 23.type
       def test: 23.type = {
                           ^
```

**Comment by milessabin** [comment]
I have no problem with the first being an error: I'd just rather it read "error: assignment to variable" ;-)

The second case is of a piece with [SI-5103](https://issues.scala-lang.org/browse/SI-5103) ... if we explicitly ask for a singleton type then the compiler shouldn't widen values out from under us.

Am I right that the latter can be worked around with a type ascription on the literal, ie. (23: 23.type)?

**Comment by folone** [comment]
@milessabin right, something like that would work:

``` scala
scala> def test: 23.type = {
     | println("panda!")
     | val res: 23.type = 23
     | res
     | }
test: 23.type
```

**Comment by folone** [comment]
Fixed the `var` rough edge in 4a4c88e

**Comment by non** [comment]
What do you make of this Jenkins failure?

http://typelevel-ci.orexio.org/job/typelevel-scala-pr/34/console

**Comment by folone** [comment]
@non Seems strange, I've just rebuilt `ant clean && ant build` locally. Worked fine.

**Comment by folone** [comment]
This last commit broke a few tests though, will look into that. Reverting until I can find a fix. One of the failing tests is related to [SI-2984](https://issues.scala-lang.org/browse/SI-2984)

**Comment by folone** [comment]
There's a better implementation in https://github.com/adriaanm/scala/pull/12, which addresses most of the issues discussed here. I'll look into porting it into this repo over the weekend.

**Comment by folone** [comment]
Closing this, as it is superseded by #86, #87, and #88.

**Pull request closed without merging**
