### PR TITLE
42.type

### PR DESCRIPTION
**Pull request by puffnfresh**
This @folone's branch, cherry-picked onto 2.11.x - opening a PR so that we can play around with it.

### CODE REVIEW

**Comment by non** [comment]
:+1: 

I think everyone agrees we want this feature, so maybe we should just merge this work and merge later fixes as needed?

**Comment by puffnfresh** [comment]
I'd like to hear from @folone before merging.

**Comment by folone** [comment]
Hey folks! This branch has ~8 failing tests. IIRC, those just need updates to the `.check` files, but I'm in a land of almost no internet atm, and cannot verify. I'll be back on Saturday evening, promise to look into this during the weekend.

**Comment by milessabin** [comment]
Yeah, we should definitely wait for @folone.

I have one comment: given that this is a patch against the compiler, why does it include a macro? Surely we could just make `SingleInhabitant` an intrinsic?

**Comment by milessabin** [comment]
See also #27.

**Comment by folone** [comment]
Sorry for the wait. So, here's the diff that needs to be applied to the branch so that it builds cleanly: https://gist.github.com/folone/c1755c105504da26c298. Those changes are – changing things like `Int(42)` to `42.type`, removing tests that did not compile previously (because of `Any` vs `AnyRef` issue), fixing bincompat.

There are more global issues that @milessabin mentioned. Namely:
- Using `Singleton` type bound instead of `SingleInhabitant` typeclass
- Reimplementing `inhabitant` function without a macro

There are other known issues that are described in the `42.type.scala` test.

**Comment by milessabin** [comment]
How would you feel about splitting the `SingletonInhabitant` part out of this for now?

I would very much like to be able to make shapeless's `Witness` and `WitnessWith` go away, but before I'm completely confident of the best way to do that I'd like to have a chance to play with the combination of this and a fix for #27.

**Comment by folone** [comment]
So, just remove `SingletonInhabitant` and `def inhabitant` for now (before we have a good solution to materialize values of singleton types)? Sure, sounds like a plan.

**Comment by milessabin** [comment]
@folone sounds good.

**Comment by puffnfresh** [comment]
See #45.

**Pull request closed without merging**
