### PR TITLE
Improved product's toString to include strings

### PR DESCRIPTION
**Pull request by mxswd**
Test frameworks and debuggers use `toString` to show string-based information to users. It helps users a lot if strings are shown with quotes.

```
scala> case class Person(name: String, age: Int)
defined class Person

scala> Person("", 0)
res0: Person = ("", 0)
```

### CODE REVIEW

**Comment by puffnfresh** [comment]
This breaks binary compatibility, seems very specialised and is strange for strings like:

```
"hello\"world"
```

Which is printed like:

```
"hello"world"
```

**Comment by mxswd** [comment]
- I'm not sure how binary compatibility is broken.
- I didn't think about printing the string. Will fix that up.
- I would like to add it to everywhere, not just product and tuple.

**Comment by puffnfresh** [comment]
I'm working under the assumption that this is necessary:

> Sources that compile under both `scalac` and `tlc` with the same flags should have the same semantics.

**Comment by mxswd** [comment]
Make `-Zreal-parametricity` instead.

**Comment by Blaisorblade** [comment]
@maxpow4h, I agree the lack of quotes is annoying, but the toString interface is forced.
I think we need a working `Show` typeclass with deriving support (I know it's more annoying). Does Scalaz not have this?

**Comment by milessabin** [comment]
Another consequence is that any projects which have tests which check the result of toString on case classes would be broken by this. That most likely includes the compiler itself.

I think there are better alternatives: using `Show` or case classes a la carte for example.

**Pull request closed without merging**
