### PR TITLE
Color REPL

### PR DESCRIPTION
**Pull request by puffnfresh**
screen shot 2014-09-22 at 9 14 21 am

### CODE REVIEW

**Comment by paulp** [comment]
Aaagh my eyes!

Just kidding.

**Comment by som-snytt** [comment]
I can't wait to see partest running ReplTest in testicolor.  What are the colors in the diff?

**Comment by puffnfresh** [comment]
@som-snytt the check is `isAnsiSupported` - think that'll be true in the tests? I wouldn't have thought so.

**Comment by som-snytt** [comment]
It's just a flag.

https://github.com/jline/jline2/blob/master/src/main/java/jline/UnixTerminal.java#L49

But I guess the check files can't be colorblind, unless partest strips the escs for the diff.

JLine supports both color and sound.

http://images.cdbaby.name/j/l/jline6_large.jpg?v=0d88b086-8e9c-46e8-b0d0-c980f04e228b

**Comment by puffnfresh** [comment]
@som-snytt the ReplTest cases passed, dunno how.

**Pull request merged**
